### PR TITLE
Fix cross compilation with openssl-sys

### LINKED ISSUE #498: v0.5.x can not be cross-build
Hello there,

I'm one of the maintainers of Vaultwarden, and there is a PR (https://github.com/dani-garcia/vaultwarden/pull/5934) opened to update to v0.5.x which is very nice, but, it doesn't seem to be able to compile for anything else but amd64/x86_64 for some reason.

The same btw for `webauthn-authenticator-rs`

### I did this

I do have to set `CC` for some reason. It doesn't seem to use `TARGET_CC` as openssl-sys normally does.
Also, if i remove the `softpasskey` feature, it does build on both targets.

```bash
git checkout v0.5.1

# Build for amd64/x86_64 works
docker run --rm -it -v "$(pwd)":/home/rust/src docker.io/blackdex/rust-musl:x86_64-musl bash -c "export CC="\${TARGET_CC}" ; cargo build -p webauthn-authenticator-rs --features softpasskey -vvv"

# Build for arm64/aarch64 breaks
docker run --rm -it -v "$(pwd)":/home/rust/src docker.io/blackdex/rust-musl:aarch64-musl bash -c "export CC="\${TARGET_CC}" ; cargo build -p webauthn-authenticator-rs --features softpasskey -vvv"
```

Also, if i checkout v0.3.2 and try to use the same images, they do work without issues.

```bash
git check v0.3.2

# Build for amd64/x86_64 works
docker run --rm -it -v "$(pwd)":/home/rust/src docker.io/blackdex/rust-musl:aarch64-musl bash -c "cargo build --example tide"

# Build for arm64/aarch64 also works
docker run --rm -it -v "$(pwd)":/home/rust/src docker.io/blackdex/rust-musl:aarch64-musl bash -c "cargo build --example tide"
```

### I expected the following

Working build.

### What actually happened

Broken build.

### Version (and git commit)

`git checkout v0.5.1`

### Operating System / Version

Arch Linux / Latest updates
or
Docker Ubuntu 24.04

### Any other comments

If you need more details, please ask!

### PR DESCRIPTION
**Pull request by BlackDex**
Because the `build.rs` code used openssl directly, openssl got build for the host architecture instead of the target architecture. This causes issues when cross compiling because some features or API's are different based upon the target architecture which then in the end causes a failed build.

This PR fixes this by using the special environment variable set by openssl-sys for downstream build.rs to check the version and act upon that.

This also removes the build-dependencies, since those are not needed anymore.

I tested this using both the https://github.com/BlackDex/rust-musl/ build images and the Debian based images using the Dockerfile.cross example which can be found here https://github.com/kanidm/webauthn-rs/issues/498#issuecomment-3026595709

Fixes #498

- [x] cargo test has been run and passes
- [x] documentation has been updated with relevant examples (if relevant)

### CODE REVIEW

File: webauthn-authenticator-rs/build.rs [hunk 1]
```diff
@@ -1,65 +1,33 @@
...
-        let expected = [
-            0x1f, 0xba, 0x3c, 0xce, 0x17, 0x62, 0x2c, 0x68, 0x26, 0x8d, 0x9f, 0x75, 0xb5, 0xa8,
-            0xa3, 0x35, 0x1b, 0x51, 0x7f, 0x9, 0x6f, 0xb5, 0xe2, 0x94, 0x94, 0x1a, 0xf7, 0xe3,
-            0xa6, 0xa8, 0xd6, 0xe1, 0xe3, 0x4f, 0x1a, 0xa3, 0x74, 0x72, 0x38, 0xc0, 0x4d, 0x3b,
-            0xd2, 0x5e, 0x7, 0xef, 0x1b, 0x35, 0xfe, 0xf3, 0x59, 0x0, 0xd, 0x75, 0x56, 0x15, 0xcd,
-            0x85, 0xbe, 0x27, 0xcf, 0xc8, 0x7, 0xd1,
-        ];
+        println!();
+        if let Ok(v) = env::var("DEP_OPENSSL_VERSION_NUMBER") {
+            let version = u64::from_str_radix(&v, 16).unwrap();
```
Comment (yaleman) [inline webauthn-authenticator-rs/build.rs:10]: This should be an expect with an explanation of what went wrong, unwraps lead to spooky outcomes.
```suggestion
            let version = u64::from_str_radix(&v, 16).expect("Failed to parse OpenSSL version in build.rs");
```

File: webauthn-authenticator-rs/build.rs [hunk 2]
```diff
@@ -1,65 +1,33 @@
...
 
-        let r: Result<[u8; 64], _> = hkdf_sha_256(&salt, &[]);
-        if !matches!(r, Ok(actual) if actual == expected) {
-            println!(
-                r#"
-Your version of OpenSSL did not perform HKDF-SHA-256 with a zero-length
-secret correctly, because of an OpenSSL bug. This issue will cause
-webauthn-authenticator-rs to malfunction.
+            if version >= 0x3_00_00_00_0 {
+                println!("OpenSSL version string: {version}");
```
Comment (yaleman) [inline webauthn-authenticator-rs/build.rs:13]: unnecessary build noise
```suggestion
```

File: webauthn-rs-core/build.rs [hunk 3]
```diff
@@ -1,22 +1,29 @@
...
-    #[allow(clippy::unusual_byte_groupings)]
-    if number() < 0x2_00_00_00_0 {
-        println!(
-            r#"
+    println!();
+    if let Ok(v) = env::var("DEP_OPENSSL_VERSION_NUMBER") {
+        let version = u64::from_str_radix(&v, 16).unwrap();
+
+        if version >= 0x3_00_00_00_0 {
+            println!("OpenSSL version string: {version}");
```
Comment (yaleman) [inline webauthn-rs-core/build.rs:11]: unnecessary build noise
```suggestion
```

File: attestation-ca/build.rs [hunk 4]
```diff
@@ -1,22 +1,29 @@
...
-    #[allow(clippy::unusual_byte_groupings)]
-    if number() < 0x2_00_00_00_0 {
-        println!(
-            r#"
+    println!();
+    if let Ok(v) = env::var("DEP_OPENSSL_VERSION_NUMBER") {
+        let version = u64::from_str_radix(&v, 16).unwrap();
+
+        if version >= 0x3_00_00_00_0 {
+            println!("OpenSSL version string: {version}");
```
Comment (yaleman) [inline attestation-ca/build.rs:11]: unnecessary build noise
```suggestion
```

File: attestation-ca/build.rs [hunk 5]
```diff
@@ -1,22 +1,29 @@
...
 
 fn main() {
-    // LibreSSL reports as OpenSSL v2 (which was skipped).
-    #[allow(clippy::unusual_byte_groupings)]
-    if number() < 0x2_00_00_00_0 {
-        println!(
-            r#"
+    println!();
+    if let Ok(v) = env::var("DEP_OPENSSL_VERSION_NUMBER") {
+        let version = u64::from_str_radix(&v, 16).unwrap();
```
Comment (yaleman) [inline attestation-ca/build.rs:8]: This should be an expect with an explanation of what went wrong, unwraps lead to spooky outcomes.
```suggestion
            let version = u64::from_str_radix(&v, 16).expect("Failed to parse OpenSSL version in build.rs");
```

File: webauthn-rs-core/build.rs [hunk 6]
```diff
@@ -1,22 +1,29 @@
...
 
 fn main() {
-    // LibreSSL reports as OpenSSL v2.
-    #[allow(clippy::unusual_byte_groupings)]
-    if number() < 0x2_00_00_00_0 {
-        println!(
-            r#"
+    println!();
+    if let Ok(v) = env::var("DEP_OPENSSL_VERSION_NUMBER") {
+        let version = u64::from_str_radix(&v, 16).unwrap();
```
Comment (yaleman) [inline webauthn-rs-core/build.rs:8]: This should be an expect with an explanation of what went wrong, unwraps lead to spooky outcomes.
```suggestion
            let version = u64::from_str_radix(&v, 16).expect("Failed to parse OpenSSL version in build.rs");
```

**Review by yaleman — CHANGES_REQUESTED** [review]

**Review by Firstyear — DISMISSED** [review]

**Comment by yaleman** [comment]
Looks like the package updates require the MSRV to be raised from 1.81 (sep 2024)

**Comment by BlackDex** [comment]
> Looks like the package updates require the MSRV to be raised from 1.81 (sep 2024)

Ah, that's because i used the latest version of openssl-sys of course. You could lower that, but that is probably not the best solution i think. Mainly because of security fixes done in both openssl crate and openssl-sys. The openssl crate version currently pinned is from August 2023.

**Comment by Firstyear** [comment]
We can raise the msrv, that's not a problem.

**Review by yaleman — APPROVED** [review]

**Comment by BlackDex** [comment]
Thanks for the merge btw!

**Comment by Firstyear** [comment]
No problem, we already released an updated version.

And again - thank you for vaultwarden, I use it personally myself, and I really like it. So if we can help out at all, let me know.
