### PR TITLE
fix(policy_verify_trust): update documentation to match default impl

### LINKED ISSUE #42: Default implementation of `policy_verify_trust` doesn't match documentation
The doc comment above the default implementation of `policy_verify_trust` says

```
/// The default implementation of this method rejects None and Uncertain attestation, and
/// will "blindly trust" self attestation and the other types as valid.
/// If you have strict security requirements we strongly recommend you implement this function,
/// and we may in the future provide a stronger default relying party policy.
```

The implementation, however, appears to accept the `None` attestation type
```
fn policy_verify_trust(&self, at: AttestationType) -> Result<Credential, ()> {
    log::debug!("policy_verify_trust -> {:?}", at);
    match at {
        AttestationType::Basic(credential, _attest_cert) => Ok(credential),
        AttestationType::Self_(credential) => Ok(credential),
        AttestationType::AttCa(credential, _attest_cert, _ca_chain) => Ok(credential),
        AttestationType::None(credential) => Ok(credential),
        _ => {
            // We don't know how to assert trust in this yet, or we just
            // don't trust it at all (Uncertain, None).
            Err(())
        }
    }
}
```

### PR DESCRIPTION
**Pull request by ericmarkmartin**
Implements #42.

- [x] cargo fmt has been run
- [x] cargo test has been run and passes
- [x] documentation has been updated with relevant examples (if relevant)

Fixes #42.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -904,22 +904,20 @@ pub trait WebauthnConfig {
     /// If the attestation statement attStmt successfully verified but is not trustworthy per step
     /// 16 above, the Relying Party SHOULD fail the registration ceremony.
     ///
-    /// The default implementation of this method rejects None and Uncertain attestation, and
+    /// The default implementation of this method rejects ECDAA and Uncertain attestation, and
```
Comment (Firstyear) [inline src/lib.rs:907]: I'd make it just "rejects Uncertain" because when we add support for ECDAA we'll "not" blindly reject it.

File: src/lib.rs [hunk 2]
```diff
@@ -904,22 +904,20 @@ pub trait WebauthnConfig {
...
-            AttestationType::AttCa(credential, _attest_cert, _ca_chain) => Ok(credential),
-            AttestationType::None(credential) => Ok(credential),
-            _ => {
-                // We don't know how to assert trust in this yet, or we just
-                // don't trust it at all (Uncertain, None).
-                Err(())
-            }
+            AttestationType::Basic(credential, _)
+            | AttestationType::Self_(credential)
+            | AttestationType::AttCa(credential, _, _)
```
Comment (Firstyear) [inline src/lib.rs:916]: I'd rather leave this "as they were" as a copy-paste example with the correct variable names to what each element of the enum is.

**Review by Firstyear — CHANGES_REQUESTED** [review]

File: src/lib.rs [hunk 3]
```diff
@@ -904,20 +904,21 @@ pub trait WebauthnConfig {
     /// If the attestation statement attStmt successfully verified but is not trustworthy per step
     /// 16 above, the Relying Party SHOULD fail the registration ceremony.
     ///
-    /// The default implementation of this method rejects ECDAA and Uncertain attestation, and
+    /// The default implementation of this method rejects None and Uncertain attestation, and
```
Comment (Firstyear) [inline src/lib.rs]: rejects Uncertain attestation :)

**Review by Firstyear — CHANGES_REQUESTED** [review]

**Comment by Firstyear** [comment]
Thank you!
